name: Create Cluster

on: [pull_request, push]

jobs:
  create-cluster:
    strategy:
      matrix:
        kubernetes-version:
          - kindest/node:v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600
          - kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb
          - kindest/node:v1.17.11@sha256:5240a7a2c34bf241afb54ac05669f8a46661912eab05705d660971eeb12f6555
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.0.0
        with:
          node_image: ${{ matrix.kubernetes-version }}
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}